In [157]:
import pandas as pd
from datetime import datetime
%pwd

'C:\\Users\\jwr19\\Documents\\Project'

In [158]:
masks_df = pd.read_csv("Public_Mask_Mandates.csv",low_memory=False)
masks_df.drop(columns=['FIPS_State', 'Effective_date', 'Expiration_date','Jurisdiction_Type', 'Issuing_Jurisdiction','FIPS_County','order_code','Effective_NA_Reason','Expiration_NA_Reason', 'Date_Signed', 
                        'origin_dataset','Source_of_Action', 'URL', 'Citation'], inplace = True)

In [142]:
masks_df.head()

,State_Tribe_Territory,County_Name,date,Current_order_status,Face_Masks_Required_in_Public,Year,Month
0,AL,Autauga County,04/10/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04
1,AL,Autauga County,04/11/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04
2,AL,Autauga County,04/12/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04
3,AL,Autauga County,04/13/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04
4,AL,Autauga County,04/14/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04

In [68]:
masks_df["Current_order_status"].value_counts()

Public Mask Mandate       613936
No Public Mask Mandate    507915
Name: Current_order_status, dtype: int64

In [69]:
date_series = masks_df["date"]
masks_df["Year"]=""
masks_df["Month"]=""
for index, row in masks_df.iterrows():
    masks_df.loc[index,"Year"] = masks_df.loc[index,"date"][6:10]
    masks_df.loc[index,"Month"] = masks_df.loc[index,"date"][:2]
#     if index == 10000:
#         break

In [80]:
masks_df.head()

,State_Tribe_Territory,County_Name,date,Current_order_status,Face_Masks_Required_in_Public,Year,Month
0,AL,Autauga County,04/10/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04
1,AL,Autauga County,04/11/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04
2,AL,Autauga County,04/12/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04
3,AL,Autauga County,04/13/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04
4,AL,Autauga County,04/14/2020 12:00:00 AM,No Public Mask Mandate,NaN,2020,04

In [112]:
masks_df_new = masks_df.groupby(by=["State_Tribe_Territory","Year","Month"])
dff_masks = masks_df_new.count()
Face_Masks_Required_in_Public = dff_masks["Face_Masks_Required_in_Public"]
Opps_to_Wear_Face_Masks_in_Public = dff_masks["date"]
dff_masks["Percent_Public_Face_Mask_Mandate"] = round(100*Face_Masks_Required_in_Public/Opps_to_Wear_Face_Masks_in_Public,2)

In [113]:
# dff_masks.to_csv("masks.csv")
dff_masks.columns

Index(['County_Name', 'date', 'Current_order_status',
       'Face_Masks_Required_in_Public', 'Percent_Public_Face_Mask_Mandate'],
      dtype='object')

In [114]:
dff_masks.drop(columns=["County_Name","date","Current_order_status","Face_Masks_Required_in_Public"],inplace=True)

In [159]:
# year = dff_masks.loc[0,"Year"]
# month = dff_masks.loc[0,"Month"]
# f"{year}-{month}"
dff_masks.head()
dff_masks.to_csv("project_one/Folder2/masks_cleaned1.csv")

In [118]:
dff_masks

                                  Percent_Public_Face_Mask_Mandate
State_Tribe_Territory Year Month
AK                    2020 04                                 0.00
                           05                                 0.00
                           06                                 0.00
                           07                                 0.00
                           08                                 0.00
...                                                            ...
WY                    2020 11                                 0.00
                           12                                 0.00
                      2021 01                                74.19
                           02                               100.00
                           03                               100.00

[672 rows x 1 columns]

In [137]:
dfff_masks = dff_masks.unstack(level=[2,1])
# dffff = dfff_masks
# dfff_masks.fillna("",inplace=True)
dfff_masks.head(50)

                      Percent_Public_Face_Mask_Mandate                  \
Month                                               04      05      06
Year                                              2020    2020    2020
State_Tribe_Territory
AK                                                0.00    0.00    0.00
AL                                                0.00    0.00    0.00
AR                                                0.00    0.00    0.00
AS                                                0.00    0.00    0.00
AZ                                                0.00    0.00    0.00
CA                                                0.00    0.00   43.33
CO                                                0.00    0.00    0.00
CT                                               52.38  100.00  100.00
DC                                                0.00   51.61  100.00
DE                                               14.29  100.00  100.00
FL                                                0.00    0.00    0.00
GA                                                0.00    0.00    0.00
GU                                                0.00   80.65  100.00
HI                                               66.67  100.00  100.00
IA                                                0.00    0.00    0.00
ID                                                0.00    0.00    0.00
IL                                                0.00  100.00  100.00
IN                                                0.00    0.00    0.00
KS                                                0.00    0.00    0.00
KY                                                0.00    0.00    0.00
LA                                                0.00    0.00    0.00
MA                                                0.00   83.87  100.00
MD                                               61.90  100.00  100.00
ME                                                0.00  100.00  100.00
MI                                               23.81  100.00  100.00
MN                                                0.00    0.00    0.00
MO                                                0.00    0.00    0.00
MP                                                0.00    0.00    0.00
MS                                                0.00    0.00    0.00
MT                                                0.00    0.00    0.00
NC                                                0.00    0.00   16.67
ND                                                0.00    0.00    0.00
NE                                                0.00    0.00    0.00
NH                                                0.00    0.00    0.00
NJ                                              100.00  100.00  100.00
NM                                                0.00   49.85  100.00
NV                                                0.00    0.00   23.33
NY                                               66.67  100.00  100.00
OH                                                0.00    0.00    0.00
OK                                                0.00    0.00    0.00
OR                                                0.00    0.00    0.00
PA                                               57.14  100.00  100.00
PR                                               85.71  100.00  100.00
RI                                                0.00   77.42  100.00
SC                                                0.00    0.00    0.00
SD                                                0.00    0.00    0.00
TN                                                0.00    0.00    0.00
TX                                                0.00    0.00    0.00
UT                                                0.00    0.00    0.00
VA                                                0.00    9.68  100.00

                                                                             \
Month                      07      08     09      10      11     12      01
Year                     2020    2020   2020    2020    2020   2020    2021
State_Tribe_Territory
AK                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
AL                      51.61  100.00  100.0  100.00  100.00  100.0  100.00
AR                      38.71  100.00  100.0  100.00  100.00  100.0  100.00
AS                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
AZ                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
CA                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
CO                      51.61  100.00  100.0  100.00  100.00  100.0  100.00
CT                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
DC                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
DE                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
FL                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
GA                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
GU                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
HI                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
IA                       0.00    0.00    0.0    0.00   46.67  100.0  100.00
ID                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
IL                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
IN                      16.13  100.00  100.0  100.00  100.00  100.0  100.00
KS                      93.55  100.00  100.0  100.00  100.00  100.0  100.00
KY                      70.97  100.00  100.0  100.00  100.00  100.0  100.00
LA                      61.29  100.00  100.0  100.00  100.00  100.0  100.00
MA                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
MD                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
ME                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
MI                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
MN                      25.81  100.00  100.0  100.00  100.00  100.0  100.00
MO                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
MP                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
MS                      12.51   91.15  100.0  100.00   56.59   77.3   93.31
MT                      54.84  100.00  100.0  100.00  100.00  100.0  100.00
NC                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
ND                       0.00    0.00    0.0    0.00   56.67  100.0  100.00
NE                       0.00    0.00    0.0    0.00   66.67  100.0  100.00
NH                       0.00    0.00    0.0    0.00   36.67  100.0  100.00
NJ                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
NM                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
NV                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
NY                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
OH                      37.50  100.00  100.0  100.00  100.00  100.0  100.00
OK                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
OR                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
PA                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
PR                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
RI                     100.00  100.00  100.0  100.00  100.00  100.0  100.00
SC                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
SD                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
TN                       0.00    0.00    0.0    0.00    0.00    0.0    0.00
TX                      93.55  100.00  100.0  100.00  100.00  100.0  100.00
UT                       0.00    0.00    0.0   49.61   94.48  100.0  100.00
VA                     100.00  100.00  100.0  100.00  100.00  100.0  100.00


Month                      02      03
Year                     2021    2021
State_Tribe_Territory
AK                       0.00    0.00
AL                     100.00  100.00
AR                     100.00  100.00
AS                      96.43  100.00
AZ                       0.00    0.00
CA                     100.00  100.00
CO                     100.00  100.00
CT                     100.00  100.00
DC                     100.00  100.00
DE                     100.00  100.00
FL                       0.00    0.00
GA                       0.00    0.00
GU                     100.00  100.00
HI                     100.00  100.00
IA                     100.00   31.82
ID                       0.00    0.00
IL                     100.00  100.00
IN                     100.00  100.00
KS                     100.00  100.00
KY                     100.00  100.00
LA                     100.00  100.00
MA                     100.00  100.00
MD                     100.00  100.00
ME                     100.00  100.00
MI                     100.00  100.00
MN                     100.00  100.00
MO                       0.00    0.00
MP                       0.00    0.00
MS                      91.46   99.22
MT                     100.00  100.00
NC                     100.00  100.00
ND                     100.00  100.00
NE                     100.00  100.00
NH                     100.00  100.00
NJ                     100.00  100.00
NM                     100.00  100.00
NV                     100.00  100.00
NY                     100.00  100.00
OH                     100.00  100.00
OK                       0.00    0.00
OR                     100.00  100.00
PA                     100.00  100.00
PR                     100.00  100.00
RI                     100.00  100.00
SC                       0.00    0.00
SD                       0.00    0.00
TN                       0.00    0.00
TX                     100.00  100.00
UT                     100.00  100.00
VA                     100.00  100.00

In [160]:
dfff_masks.to_csv("project_one/Folder2/masks_cleaned2.csv")